"""alter price fields in models

Revision ID: 0f3f5780fdfb
Revises: 2c91bbc371fd
Create Date: 2025-05-04 21:42:39.554504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3f5780fdfb'
down_revision: Union[str, None] = '2c91bbc371fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'total_price')
    op.drop_column('order_items', 'price_at_order')
    # ### end Alembic commands ###
