"""add status_id field to orders table

Revision ID: 261fd728b023
Revises: 9e12a940872c
Create Date: 2025-05-10 10:24:56.643291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261fd728b023'
down_revision: Union[str, None] = '9e12a940872c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'])
    orders_table = sa.table('orders', sa.Column('status_id', sa.Integer))
    op.execute(orders_table.update().values(status_id=1))
    op.alter_column('orders', 'status_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status_id')
    # ### end Alembic commands ###
