"""add id_deleted field to address model

Revision ID: 3c5dd3c4dc8e
Revises: f3bdce210655
Create Date: 2025-05-07 11:37:00.677914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5dd3c4dc8e'
down_revision: Union[str, None] = 'f3bdce210655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.add_column('addresses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    addresses_table = sa.table('addresses', sa.Column('is_deleted', sa.Boolean))
    op.execute(addresses_table.update().values(is_deleted=False))
    op.alter_column('addresses', 'is_deleted', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'is_deleted')
    # ### end Alembic commands ###
