"""quantity_in_stock field for product

Revision ID: 4c043ab00841
Revises: 0f3f5780fdfb
Create Date: 2025-05-06 09:49:15.434974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c043ab00841'
down_revision: Union[str, None] = '0f3f5780fdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('quantity_in_stock', sa.Integer(), nullable=True))
    products_table = sa.table('products', sa.column('quantity_in_stock', sa.Integer))
    op.execute(products_table.update().values(quantity_in_stock=0))
    op.alter_column('products', 'quantity_in_stock', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_in_stock')
    # ### end Alembic commands ###
