"""addresses table, update orders table

Revision ID: 61025fc05aae
Revises: 4c043ab00841
Create Date: 2025-05-06 16:54:24.195297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61025fc05aae'
down_revision: Union[str, None] = '4c043ab00841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.CheckConstraint('char_length(trim(address)) > 0', name='check_name_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'])
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('phone', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'address_id')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_table('addresses')
    # ### end Alembic commands ###
