"""add order_statuses table

Revision ID: 9e12a940872c
Revises: 8f80fbfcdecc
Create Date: 2025-05-10 10:07:10.695232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e12a940872c'
down_revision: Union[str, None] = '8f80fbfcdecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('status_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('status')
    )

    statuses = [
        {'status': 'created', 'status_name': 'Создан'},
        {'status': 'canceled', 'status_name': 'Отменён'},
        {'status': 'in_progress', 'status_name': 'В процессе'},
        {'status': 'delivered', 'status_name': 'Доставлен'},
        {'status': 'completed', 'status_name': 'Завершён'},
    ]

    order_statuses_table = sa.table(
        'order_statuses',
        sa.column('status', sa.String),
        sa.column('status_name', sa.String)
    )

    op.bulk_insert(order_statuses_table, statuses)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_statuses')
    # ### end Alembic commands ###
